### ISSUE TITLE
Checklist before deployment

### ISSUE THREAD

**Issue by jjcrab** [jjcrab/the-art-den-backend#2]
- [ ] last minute troubleshooting
- [ ] update Readme
- [ ] deploy to heroku
- [ ] deploy to AWS S3
- [ ] add deploy link to GitHub about
- [ ] add backend link to frontend ReadMe
